sudo: false
language: node_js
branches:
  only:
      - master
notifications:
  email: false
node_js:
  - "6"
before_install:
  - npm i -g npm@3
  - npm i -g bower
  - bower install
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
